### ISSUE TITLE
Library project

### ISSUE THREAD

**Issue by vikramkakkar** [vbauer/android-arsenal.com#226]
Hi,

It seems that the `contact` functionality of the site is having some issue(s). I am trying to submit the following library to your site:

SublimeNavigationView: https://github.com/vikramkakkar/SublimeNavigationView

But, my attempts have been unsuccessful.

Also, is there a tutorial/guide to adding the `Android-Arsenal` badge that I see on lots of projects?

**Comment by vbauer** [comment]
Sorry for a long response, we have a lot of projects in queue. I've just added SublimeNavigationView on the site. It's available here: http://android-arsenal.com/details/1/3043

> Also, is there a tutorial/guide to adding the Android-Arsenal badge that I see on lots of projects?

You can you use `"Generate"` link on the details page with project. Ex:
```
[![Android Arsenal](https://img.shields.io/badge/Android%20Arsenal-SublimeNavigationView-brightgreen.svg?style=flat)](http://android-arsenal.com/details/1/3043)
```

Thank you for contribution!

**Comment by vikramkakkar** [comment]
@vbauer Thanks, Vladislav. I apologize for my impatience. I wasn't sure if the submission was going through or not. For future reference, should I open an `issue` here, or use the `Contact` link on Android-Arsenal website?

Thanks again, for listing my project!

**Comment by vbauer** [comment]
No problem, you can use both variants. I check all of them. :)
