### ISSUE TITLE
The favorites count doesn't update.

### ISSUE THREAD

**Issue by rsavin** [vbauer/android-arsenal.com#230]
Favorites count is static and it saves the number which was before adding a library to android arsenal.  Could you make this value updatable for reflecting actual information?

**Comment by vbauer** [comment]
@rsavin Hello! Could you please provide information about your browser and OS? It will be also useful to have some steps to reproduce this issue, because I can't repeat it on OS X & Google Chrome.

**Comment by rsavin** [comment]
OS X 10.11.2
Firefox 40.0.3 and Chromium 41.0.2223.0
Steps : Just open any project

![123](https://cloud.githubusercontent.com/assets/1546352/12451558/3576fde6-bf9b-11e5-9672-6a4b7203c77a.png)

**Comment by rsavin** [comment]
I suddenly understood that the favorites number is a feature of android arsenal and it doesn't reflect stars on github. There is no bug, sorry :)

**Comment by vbauer** [comment]
Yep, sorry, I have not got enough time to write an answer. :)
