### ISSUE TITLE
Add project

### ISSUE THREAD

**Issue by Nightonke** [vbauer/android-arsenal.com#235]
Hello, could you please add this project: https://github.com/Nightonke/CoCoin
Thanks!

**Comment by vbauer** [comment]
@Nightonke Hello, could you please suggest tag/category for this project?

**Comment by vbauer** [comment]
@Nightonke ping

**Comment by vbauer** [comment]
I'm going to close this ticket for now
If you'd like to add this project again, please reopen issue or create a new one
