### ISSUE TITLE
Change category for Anvil

### ISSUE THREAD

**Issue by zserge** [vbauer/android-arsenal.com#244]
May I ask you to change the category of Anvil library?

http://android-arsenal.com/details/1/1894

Currently it's listed under "Layouts" category, however it's not a custom layout or a view group, it's a library for building reactive UI with data binding and event listener injection, so the current category may confuse users.

Could you please change the category to "Architecture" (preferred) or "Dependency injection"?

Also, the latest version listed on Android Arsenal is 0.0.6, while the most recent version of Anvil by today is 0.3.1.

**Comment by vbauer** [comment]
Thank you for found mistake! I've just change the category to "Architecture".
