### ISSUE TITLE
Add Project

### ISSUE THREAD

**Issue by SpongeBobSun** [vbauer/android-arsenal.com#270]
Project link - https://github.com/PuffOpenSource/Puff-Android

Short description - Open Source Offline Password Manager for Android

Use tag v0.9 if you need a release APK file.

Thanks.

**Comment by SpongeBobSun** [comment]
@vbauer Ping...

BTW this app is available at google play.  Search Puff password manager and you will find it .

**Comment by vbauer** [comment]
@SpongeBobSun Hello, you need to use this form: http://android-arsenal.com/contact

**Comment by SpongeBobSun** [comment]
@vbauer Submitted via above form. But I hit the submit button too quick that I forgot to add the playstore link. Is there anyway to re-fill the form? Or could you guys help me to add it? The link is - https://play.google.com/store/apps/details?id=sun.bob.leela

**Comment by vbauer** [comment]
@SpongeBobSun You can put this link in README file. AA fetches information from Github after submission.

**Comment by SpongeBobSun** [comment]
@vbauer Done.

**Comment by vbauer** [comment]
https://android-arsenal.com/details/3/4893
